In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('C:/Users/LENOVO/Downloads/fmcg_sales_marketing_profitability_2023_2025.csv')

In [5]:
df.shape

(18240, 27)

In [6]:
df.head(15)

,Order_ID,Order_Date,Year,Quarter,Month,Month_Name,Region,Country,City,Sales_Person,...,Units_Sold,Unit_Price_USD,Discount_Pct,Gross_Sales_USD,Marketing_Spend_USD,COGS_USD,Logistics_Cost_USD,Net_Revenue_USD,Profit_USD,Profit_Margin_Pct
0,FMCG-2025-000001,2025-09-26,2025,Q3,9,September,Oceania,Australia,Perth,Ethan Cole,...,73,8.47,8.94,618.31,66.05,314.09,43.03,563.03,139.86,24.84
1,FMCG-2024-000002,2024-10-09,2024,Q4,10,October,Asia,India,Mumbai,Meera Nair,...,99,2.89,9.86,286.11,35.26,123.79,23.89,257.90,74.96,29.07
2,FMCG-2024-000003,2024-07-06,2024,Q3,7,July,North America,USA,Los Angeles,Nina Booker,...,361,5.96,15.32,2151.56,171.46,1011.60,107.02,1821.94,531.86,29.19
3,FMCG-2024-000004,2024-05-25,2024,Q2,5,May,Europe,France,Paris,Oliver Kent,...,603,3.80,18.00,2291.40,118.39,1133.66,85.20,1878.95,541.70,28.83
4,FMCG-2023-000005,2023-08-10,2023,Q3,8,August,Europe,France,Lyon,Lucas Bennett,...,113,3.18,12.46,359.34,34.82,157.70,23.02,314.57,99.03,31.48
5,FMCG-2025-000006,2025-05-27,2025,Q2,5,May,Asia,Thailand,Bangkok,Nikhil Bhat,...,101,2.92,14.59,294.92,29.48,120.91,17.04,251.89,84.46,33.53
6,FMCG-2025-000007,2025-03-19,2025,Q1,3,March,Asia,India,Hyderabad,Farah Siddiqui,...,155,4.83,8.32,748.65,75.17,404.53,45.67,686.36,160.99,23.46
7,FMCG-2025-000008,2025-01-24,2025,Q1,1,January,Europe,UK,Manchester,Marco Bellini,...,134,6.61,13.00,885.74,131.22,428.37,86.74,770.59,124.26,16.13
8,FMCG-2025-000009,2025-03-08,2025,Q1,3,March,Europe,Italy,Milan,Elena Dupont,...,18,4.81,8.82,86.58,13.21,44.24,9.68,78.94,11.81,14.96
9,FMCG-2024-000010,2024-12-23,2024,Q4,12,December,South America,Colombia,Medellin,Lucia Herrera,...,328,4.08,17.88,1338.24,64.11,579.88,80.71,1098.96,374.26,34.06
10,FMCG-2025-000011,2025-09-20,2025,Q3,9,September,Europe,UK,London,Lucas Bennett,...,17,3.08,12.95,52.36,8.59,30.47,4.96,45.58,1.56,3.42
11,FMCG-2023-000012,2023-03-14,2023,Q1,3,March,South America,Chile,Valparaiso,Mateo Silva,...,16,2.71,4.84,43.36,6.41,27.85,5.59,41.26,1.41,3.42
12,FMCG-2025-000013,2025-02-27,2025,Q1,2,February,South America,Brazil,Sao Paulo,Mateo Silva,...,26,3.41,4.99,88.66,14.07,52.14,6.26,84.24,11.77,13.97
13,FMCG-2024-000014,2024-09-23,2024,Q3,9,September,Europe,Spain,Madrid,Marco Bellini,...,542,4.24,16.36,2298.08,198.69,1229.53,119.54,1922.11,374.35,19.48
14,FMCG-2023-000015,2023-12-31,2023,Q4,12,December,Europe,France,Lyon,Lucas Bennett,...,36,3.15,13.40,113.40,21.80,65.28,9.65,98.20,1.47,1.50

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18240 entries, 0 to 18239
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Order_ID             18240 non-null  object
 1   Order_Date           18240 non-null  object
 2   Year                 18240 non-null  int64
 3   Quarter              18240 non-null  object
 4   Month                18240 non-null  int64
 5   Month_Name           18240 non-null  object
 6   Region               18240 non-null  object
 7   Country              18240 non-null  object
 8   City                 18240 non-null  object
 9   Sales_Person         18240 non-null  object
 10  Customer_Type        18240 non-null  object
 11  Sales_Channel        18240 non-null  object
 12  Promotion_Type       18240 non-null  object
 13  Product_Category     18240 non-null  object
 14  Brand                18240 non-null  object
 15  Product_Name         18240 non-null  object
 16  SKU                  18240 non-null  object
 17  Units_Sold           18240 non-null  int64
 18  Unit_Price_USD       18240 non-null  float64
 19  Discount_Pct         18240 non-null  float64
 20  Gross_Sales_USD      18240 non-null  float64
 21  Marketing_Spend_USD  18240 non-null  float64
 22  COGS_USD             18240 non-null  float64
 23  Logistics_Cost_USD   18240 non-null  float64
 24  Net_Revenue_USD      18240 non-null  float64
 25  Profit_USD           18240 non-null  float64
 26  Profit_Margin_Pct    18240 non-null  float64
dtypes: float64(9), int64(3), object(15)
memory usage: 3.8+ MB

In [11]:
df.describe()

,Year,Month,Units_Sold,Unit_Price_USD,Discount_Pct,Gross_Sales_USD,Marketing_Spend_USD,COGS_USD,Logistics_Cost_USD,Net_Revenue_USD,Profit_USD,Profit_Margin_Pct
count,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000,18240.000000
mean,2024.001590,6.519024,212.909759,4.467254,12.935771,936.431746,85.741888,471.024278,54.031789,792.210526,181.412572,19.870780
std,0.816752,3.467308,202.102318,1.949341,5.735972,1045.606955,87.551045,537.351019,51.266996,861.237271,239.526879,10.569275
min,2023.000000,1.000000,5.000000,1.450000,0.000000,13.020000,1.810000,6.310000,1.080000,10.540000,-637.500000,-45.310000
25%,2023.000000,3.000000,70.000000,3.020000,8.710000,274.532500,33.495000,140.510000,21.370000,245.217500,32.345000,13.720000
50%,2024.000000,7.000000,139.000000,3.990000,12.690000,565.430000,61.385000,287.165000,38.985000,493.895000,91.890000,20.870000
75%,2025.000000,10.000000,288.000000,5.440000,16.850000,1213.835000,107.605000,599.790000,69.240000,1027.362500,239.117500,27.260000
max,2025.000000,12.000000,1366.000000,12.740000,28.000000,10634.120000,1767.710000,6473.330000,628.860000,8752.940000,2723.000000,44.490000

In [8]:
print(df['Marketing_Spend_USD'].sum())

1563932.0299999998

In [10]:
df.isnull().sum()

Order_ID               0
Order_Date             0
Year                   0
Quarter                0
Month                  0
Month_Name             0
Region                 0
Country                0
City                   0
Sales_Person           0
Customer_Type          0
Sales_Channel          0
Promotion_Type         0
Product_Category       0
Brand                  0
Product_Name           0
SKU                    0
Units_Sold             0
Unit_Price_USD         0
Discount_Pct           0
Gross_Sales_USD        0
Marketing_Spend_USD    0
COGS_USD               0
Logistics_Cost_USD     0
Net_Revenue_USD        0
Profit_USD             0
Profit_Margin_Pct      0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df['Order_ID'].unique

<bound method Series.unique of 0        FMCG-2025-000001
1        FMCG-2024-000002
2        FMCG-2024-000003
3        FMCG-2024-000004
4        FMCG-2023-000005
               ...
18235    FMCG-2023-018236
18236    FMCG-2023-018237
18237    FMCG-2025-018238
18238    FMCG-2023-018239
18239    FMCG-2024-018240
Name: Order_ID, Length: 18240, dtype: object>

In [13]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
df.to_csv('cleaned_fmcg_data.csv', index=False)